Zimbra/zimlet-cli

- README.md
- package.json
- src/cli.js
- src/index.js
- src/lib/webpack/transform-config.js
This implements a mechanism for customizing Webpack config, very similar to the implementation found in [`developit/preact-cli`](https://github.com/developit/preact-cli).
> Custom Config

- build-shims.js
- package-lock.json
- package.json
- src/index.js
- src/shims/index.js
- src/shims/preact-compat.js
- src/shims/preact-redux.js
- src/shims/preact-router.js
- src/shims/preact.js
- src/shims/react-apollo.js
I mocked out some of the peer deps of the shimmed files to avoid adding more devDeps.
Curious on your thoughts to this approach to easy maintainability of the named exports.
> Auto build shims

- package-lock.json
- package.json
- src/commands/package.js
Adds a `zimbraXVersion` option to the `package` command to set the `zimbraXZimletCompatibleSemVer` attribute in the Zimlet manifest.
`zimbraXZimletCompatibleSemVer` is the version of Zimbra X this Zimlet requires.
> PREAPPS-121: Use server resource consolidation to get Zimlets

- .github/CODEOWNERS
- package.json
- Revert css-loader upgrade as it involves config changes
> PREAPPS-199 PREAPPS-199 Zimletize Restore Contacts

- build-shims.js
- src/shims/index.js
- src/shims/preact-pwa-install/index.js
Zimlet to install Progressive Web App
> PREAPPS-2309: Progressive Web App Zimlet

- build-shims.js
- src/shims/@zimbra-client/enhancers/index.js
Added `withIntlWrapper` enhancer.
> PREAPPS-2535: Zimlet localization support

- README.md
- package-lock.json
- package.json
See also https://github.com/ZimbraOS/zm-x-web/pull/1743.
> Added shims for FormGroup and AlignedLabel components.

- src/entry.js
Expose the redux store as a global.
> PREAPPS-3084: 

- build-shims.js
- package-lock.json
- package.json
- src/shims/@zimbra-client/components/index.js
- src/shims/@zimbra-client/errors/index.js
- src/shims/@zimbra-client/graphql/index.js
- src/shims/index.js
- src/shims/recompose/index.js
Changes:
1. Shimmed dependencies needed for PREAPPS-3699.
> [Do not merge]PREAPPS-3699: added shimmed dependencies.

- build-shims.js
- src/shims/@zimbra-client/graphql/index.js
Export withSetCustomMetaData, withGetCustomMetaData decorators to use in zimlets
> PREAPPS-4827: Implement GetCustomMetadata and SetCustomMetadata to GraphQL

- src/commands/package.js
Changes:
1. Added 'label' attribute to zimlet xml
> PREAPPS-4260 || PREAPPS-4652: Support for showing display names for Zimbra X zimlets on admin UI

- build-shims.js
- src/shims/@zimbra-client/browser/index.js
- src/shims/index.js
- add isDesktopApp and openExternalBrowser
> PREAPPS-4721 Application links should be handled by desktop app, not external browser

- build-shims.js
- src/shims/@zimbra-client/components/index.js
- src/shims/@zimbra-client/graphql/index.js
Added component FolderListLight in the list of components available to zimlets
> PREAPPS-4957: Make component FolderListLight available for zimlets

- build-shims.js
- src/shims/@zimbra-client/components/index.js
- Added components for toolbar and sidebar which are exposed by zm-x-web.
> PREAPPS-5142: added generic sidebar and toolbar for mobile screen

- package-lock.json
- package.json
- src/index.js
Dynamically choose devServer port starting with the configured port.
> ZX-1954: [zimlet-cli] Add dynamic port choosing

- build-shims.js
- src/shims/@zimbra-client/components/index.js
- src/shims/@zimbra-client/graphql/index.js
- src/shims/@zimbra-client/util/index.js
Added soap api calls for certificate management.
Making those calls available into zimlet via shims.
> PREAPPS-6192 Adding more shims for certificate info.

- build-shims.js
- src/shims/@zimbra-client/components/index.js
Include the SignatureBox component.
> PREAPPS-7028: Implement plain text Signature in Modern UI

- build-shims.js
- src/shims/@zimbra-client/constants/index.js
Linking constants from zm-x-web to zm-modern-zimlets
> PREAPPS-7359: Disable Mail recall option When recalling a message with users outside the user's domain 

- build-shims.js
- src/shims/@zimbra-client/hooks/graphql/index.js
- Exposed the `useCreateFolderMutation` and `useFolderActionMutation` for the zimlet.
> PREAPPS-7575: How to move an email and refresh the mail list view from Modern UI Zimlet

- build-shims.js
- src/shims/@zimbra-client/components/index.js
- src/shims/@zimbra-client/hooks/graphql/index.js
- src/shims/@zimbra-client/util/index.js
This PR exposes the following to zimlets:
1. filterNonInsertableCalendars - Utility function
2. useCalendarsData - Hook
3. CalendarOptionItem - Component
> PREAPPS-7891 Import ICS files to calendar 

- build-shims.js
- src/shims/@zimbra-client/components/index.js
- src/shims/@zimbra-client/constants/index.js
- src/shims/@zimbra-client/hooks/index.js
Exposed following components to support attachment alert functionality
1. HelpTooltip component
2. useOriginalMsgHeader hook
> PREAPPS-7932: Exposed HelpTooltip component and useOriginalMsgHeader hook

- build-shims.js
- src/shims/@zimbra-client/util/index.js
- exposing htmlEncode and getElectronIpc(for electronIpc communication)
> PREAPPS-8156 Implementation of Auto-Update Zimbra Desktop part-2

- package-lock.json
- package.json
redux-actions,  copy-webpack-plugin
> PREAPPS-7871: Updated versions of redux-actions, copy-webpack-plugin
